# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8090
    context-path: /

# mysql
spring:
    datasource:
      dynamic:
        primary: gen
        datasource:
          gen: 
            driver-class-name: com.mysql.jdbc.Driver
            url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.12.101:3306/hzero_generator?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
            username: ${SPRING_DATASOURCE_USERNAME:root}
            password: ${SPRING_DATASOURCE_PASSWORD:root}
          dev: 
            driver-class-name: com.mysql.jdbc.Driver
            url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.12.102:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
            username: ${SPRING_DATASOURCE_USERNAME:root}
            password: ${SPRING_DATASOURCE_PASSWORD:root}
          tst: 
            driver-class-name: com.mysql.jdbc.Driver
            url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.12.101:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
            username: ${SPRING_DATASOURCE_USERNAME:root}
            password: ${SPRING_DATASOURCE_PASSWORD:root}
          uat: 
            driver-class-name: com.mysql.jdbc.Driver
            url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.12.101:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
            username: ${SPRING_DATASOURCE_USERNAME:root}
            password: ${SPRING_DATASOURCE_PASSWORD:root}
          prd: 
            driver-class-name: com.mysql.jdbc.Driver
            url: ${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.12.101:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
            username: ${SPRING_DATASOURCE_USERNAME:root}
            password: ${SPRING_DATASOURCE_PASSWORD:root}
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/view/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

