# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    context-path: /

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.20.0.202:3306/hzero_generator?useUnicode=true&characterEncoding=UTF-8
        username: hzero
        password: hzero
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/view/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

