# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8090
    context-path: /

# mysql
spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://172.20.0.202:3306/hzero_generator?useUnicode=true&characterEncoding=UTF-8}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:root}
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/view/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

